config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      post 'signup' => 'users#signup'
      post 'login' => 'users#login'
      post 'logout' => 'users#logout'
    end
  end

  resources :users
  resources :game_results
  resources :games

end

app/models/game_result.rb
class GameResult < ActiveRecord::Base
end

app/controllers/game_results_controller.rb
class GameResultsController < ApplicationController
  before_action :set_game_result, only: [:show, :edit, :update, :destroy]

  # GET /game_results
  # GET /game_results.json
  def index
    @game_results = GameResult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @game_results }
    end
  end

  # GET /game_results/1
  # GET /game_results/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game_result }
    end
  end

  # GET /game_results/new
  def new
    @game_result = GameResult.new
  end

  # GET /game_results/1/edit
  def edit
  end

  # POST /game_results
  # POST /game_results.json
  def create
    @game_result = GameResult.new()
    @game_result.game_id = game_result_params[:game_id]
    @game_result.user_id = game_result_params[:user_id]  # TODO: use client's user id
    @game_result.result = game_result_params[:result].to_json

    respond_to do |format|
      # TODO: wait rival's result and return
      if @game_result.save
        format.html { redirect_to @game_result, notice: 'Game result was successfully created.' }
        format.json { render json: @game_result.result, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @game_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_results/1
  # PATCH/PUT /game_results/1.json
  def update
    respond_to do |format|
      if @game_result.update(game_result_params)
        format.html { redirect_to @game_result, notice: 'Game result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_results/1
  # DELETE /game_results/1.json
  def destroy
    @game_result.destroy
    respond_to do |format|
      format.html { redirect_to game_results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_result
      @game_result = GameResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_result_params
      # params.require(:game_result).permit(:game_id, :user_id, :problem_id, :correct, :consumed_time)
      params.require(:game_result).permit(:game_id, :user_id, result: [:problem_id, :correct, :consumed_time])
    end
end

app/helpers/game_results_helper.rb
module GameResultsHelper
end

app/views/game_results/_form.html.erb
<%= form_for(@game_result) do |f| %>
  <% if @game_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_result.errors.count, "error") %> prohibited this game_result from being saved:</h2>

      <ul>
      <% @game_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.number_field :problem_id %>
  </div>
  <div class="field">
    <%= f.label :correct %><br>
    <%= f.check_box :correct %>
  </div>
  <div class="field">
    <%= f.label :consumed_time %><br>
    <%= f.number_field :consumed_time %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_results/edit.html.erb
<h1>Editing game_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_result %> |
<%= link_to 'Back', game_results_path %>

app/views/game_results/index.html.erb
<h1>Listing game_results</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>User</th>
      <th>Problem</th>
      <th>Correct</th>
      <th>Consumed time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @game_results.each do |game_result| %>
      <tr>
        <td><%= game_result.game_id %></td>
        <td><%= game_result.user_id %></td>
        <td><%= game_result.problem_id %></td>
        <td><%= game_result.correct %></td>
        <td><%= game_result.consumed_time %></td>
        <td><%= game_result.result %></td>
        <td><%= link_to 'Show', game_result %></td>
        <td><%= link_to 'Edit', edit_game_result_path(game_result) %></td>
        <td><%= link_to 'Destroy', game_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game result', new_game_result_path %>

app/views/game_results/new.html.erb
<h1>New game_result</h1>

<%= render 'form' %>

<%= link_to 'Back', game_results_path %>

app/views/game_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game_result.game_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @game_result.user_id %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @game_result.problem_id %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @game_result.correct %>
</p>

<p>
  <strong>Consumed time:</strong>
  <%= @game_result.consumed_time %>
</p>

<p>
  <strong>Result:</strong>
  <%= @game_result.result %>
</p>

<%= link_to 'Edit', edit_game_result_path(@game_result) %> |
<%= link_to 'Back', game_results_path %>